import {
  CUBRIMIENTO_IMG as Cubrimiento,
  CUBRIMIENTO_TWO_IMG as CubrimientoTwo,
  CUBRIMIENTO_THREE_IMG as CubrimientoThree,
  CUBRIMIENTO_FOUR_IMG as CubrimientoFour,
  CUBRIMIENTO_FIVE_IMG as CubrimientoFive,
  CUBRIMIENTO_SIX_IMG as CubrimientoSix,
  SOCIAL_CAMPAIGNS_IMG as SocialCampaigns,
  SOCIAL_CAMPAIGNS_TWO_IMG as SocialCampaignsTwo,
  SOCIAL_CAMPAIGNS_THREE_IMG as SocialCampaignsThree,
  SOCIAL_CAMPAIGNS_FOUR_IMG as SocialCampaignsFour,
  SOCIAL_CAMPAIGNS_FIVE_IMG as SocialCampaignsFive,
  SOCIAL_MEDIA_IMG as SocialMedia,
  SOCIAL_MEDIA_TWO_IMG as SocialMediaTwo,
  SOCIAL_MEDIA_THREE_IMG as SocialMediaThree,
  SOCIAL_MEDIA_FOUR_IMG as SocialMediaFour,
  SOCIAL_MEDIA_FIVE_IMG as SocialMediaFive,
  COBRANDING_TWO_IMG as CobrandingTwo,
  COBRANDING_THREE_IMG as CobrandingThree,
  COBRANDING_FOUR_IMG as CobrandingFour,
  COBRANDING_FIVE_IMG as CobrandingFive,
  COBRANDING_SIX_IMG as CobrandingSix,
  INFOGRAPHIC_IMG as Infographic,
  INFOGRAPHIC_TWO_IMG as InfographicTwo,
  INFOGRAPHIC_THREE_IMG as InfographicThree,
  INFOGRAPHIC_FOUR_IMG as InfographicFour,
  INFOGRAPHIC_FIVE_IMG as InfographicFive,
} from "../../../assets/cloudinaryImages";

const portfolioData = [
  {
    id: 0,
    title: "communications.portfolio.opcions.one",
    image: null,
  },
  {
    id: 1,
    title: "communications.portfolio.opcions.three",
    image: Cubrimiento,
    colSpan: 2,
    rowSpan: 2,
    images: [
      { src: CubrimientoTwo, colSpan: 2, rowSpan: 2 },
      { src: CubrimientoThree, colSpan: 1, rowSpan: 1 },
      { src: CubrimientoFour, colSpan: 1, rowSpan: 1 },
      { src: CubrimientoFive, colSpan: 1, rowSpan: 1 },
      { src: CubrimientoSix, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    id: 2,
    title: "communications.portfolio.opcions.two",
    image: SocialCampaigns,
    colSpan: 1,
    rowSpan: 1,
    // images: [{ src, colSpan, rowSpan }] — first image is featured (2×2), rest are 1×1
    images: [
      { src: SocialCampaignsTwo, colSpan: 1, rowSpan: 2 },
      { src: SocialCampaignsThree, colSpan: 1, rowSpan: 2 },
      { src: SocialCampaignsFour, colSpan: 1, rowSpan: 2 },
      { src: SocialCampaignsFive, colSpan: 1, rowSpan: 2 },
    ],
  },
  {
    id: 3,
    title: "communications.portfolio.opcions.four",
    image: SocialMedia,
    colSpan: 1,
    rowSpan: 1,
    images: [
      { src: SocialMediaTwo, colSpan: 1, rowSpan: 2 },
      { src: SocialMediaThree, colSpan: 1, rowSpan: 2 },
      { src: SocialMediaFour, colSpan: 1, rowSpan: 2 },
      { src: SocialMediaFive, colSpan: 1, rowSpan: 2 },
    ],
  },
  {
    id: 4,
    title: "communications.portfolio.opcions.five",
    image: CobrandingFive,
    colSpan: 1,
    rowSpan: 1,
    images: [
      { src: CobrandingTwo, colSpan: 1, rowSpan: 2 },
      { src: CobrandingThree, colSpan: 1, rowSpan: 2 },
      { src: CobrandingFour, colSpan: 1, rowSpan: 2 },
      { src: CobrandingFive, colSpan: 1, rowSpan: 1 },
      { src: CobrandingSix, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    id: 5,
    title: "communications.portfolio.opcions.six",
    image: Infographic,
    colSpan: 1,
    rowSpan: 1,
    images: [
      { src: InfographicTwo, colSpan: 1, rowSpan: 2 },
      { src: InfographicThree, colSpan: 1, rowSpan: 2 },
      { src: InfographicFour, colSpan: 1, rowSpan: 2 },
      { src: InfographicFive, colSpan: 1, rowSpan: 2 },
    ],
  },
];

export default portfolioData;
