export const highlightCards = [
  {
    id: "sebu",
    icon: "database",
    variant: "yellow",
    codeKey: "dataAnalytics.highlights.cards.sebu.code",
    metricKey: "dataAnalytics.highlights.cards.sebu.metric",
    metricLabelKey: "dataAnalytics.highlights.cards.sebu.metricLabel",
    titleKey: "dataAnalytics.highlights.cards.sebu.title",
    descriptionKey: "dataAnalytics.highlights.cards.sebu.description",
  },
  {
    id: "lda",
    icon: "chart",
    variant: "blue",
    codeKey: "dataAnalytics.highlights.cards.lda.code",
    metricKey: "dataAnalytics.highlights.cards.lda.metric",
    metricLabelKey: "dataAnalytics.highlights.cards.lda.metricLabel",
    titleKey: "dataAnalytics.highlights.cards.lda.title",
    descriptionKey: "dataAnalytics.highlights.cards.lda.description",
  },
  {
    id: "isi",
    icon: "check",
    variant: "yellow",
    codeKey: "dataAnalytics.highlights.cards.isi.code",
    metricKey: "dataAnalytics.highlights.cards.isi.metric",
    metricLabelKey: "dataAnalytics.highlights.cards.isi.metricLabel",
    titleKey: "dataAnalytics.highlights.cards.isi.title",
    descriptionKey: "dataAnalytics.highlights.cards.isi.description",
  },
  {
    id: "rtd",
    icon: "grid",
    variant: "blue",
    codeKey: "dataAnalytics.highlights.cards.rtd.code",
    metricKey: "dataAnalytics.highlights.cards.rtd.metric",
    metricLabelKey: "dataAnalytics.highlights.cards.rtd.metricLabel",
    titleKey: "dataAnalytics.highlights.cards.rtd.title",
    descriptionKey: "dataAnalytics.highlights.cards.rtd.description",
  },
];
