export const highlightCards = [
  {
    id: "one",
    icon: "database",
    variant: "yellow",
    codeKey: "dataAnalytics.highlights.cards.one.code",
    metricKey: "dataAnalytics.highlights.cards.one.metric",
    metricLabelKey: "dataAnalytics.highlights.cards.one.metricLabel",
    titleKey: "dataAnalytics.highlights.cards.one.title",
    descriptionKey: "dataAnalytics.highlights.cards.one.description",
  },
  {
    id: "two",
    icon: "chart",
    variant: "blue",
    codeKey: "dataAnalytics.highlights.cards.two.code",
    metricKey: "dataAnalytics.highlights.cards.two.metric",
    metricLabelKey: "dataAnalytics.highlights.cards.two.metricLabel",
    titleKey: "dataAnalytics.highlights.cards.two.title",
    descriptionKey: "dataAnalytics.highlights.cards.two.description",
  },
  {
    id: "three",
    icon: "check",
    variant: "yellow",
    codeKey: "dataAnalytics.highlights.cards.three.code",
    metricKey: "dataAnalytics.highlights.cards.three.metric",
    metricLabelKey: "dataAnalytics.highlights.cards.three.metricLabel",
    titleKey: "dataAnalytics.highlights.cards.three.title",
    descriptionKey: "dataAnalytics.highlights.cards.three.description",
  },
  {
    id: "four",
    icon: "grid",
    variant: "blue",
    codeKey: "dataAnalytics.highlights.cards.four.code",
    metricKey: "dataAnalytics.highlights.cards.four.metric",
    metricLabelKey: "dataAnalytics.highlights.cards.four.metricLabel",
    titleKey: "dataAnalytics.highlights.cards.four.title",
    descriptionKey: "dataAnalytics.highlights.cards.four.description",
  },
];
