export const techTabs = [
  { id: "all", labelKey: "dataAnalytics.stack.tabs.all" },
  { id: "visualization", labelKey: "dataAnalytics.stack.tabs.visualization" },
  { id: "analysis", labelKey: "dataAnalytics.stack.tabs.analysis" },
  { id: "frontend", labelKey: "dataAnalytics.stack.tabs.frontend" },
  { id: "backend", labelKey: "dataAnalytics.stack.tabs.backend" },
  { id: "data", labelKey: "dataAnalytics.stack.tabs.data" },
  { id: "design", labelKey: "dataAnalytics.stack.tabs.design" },
  { id: "devops", labelKey: "dataAnalytics.stack.tabs.devops" },
  { id: "measurement", labelKey: "dataAnalytics.stack.tabs.measurement" },
];

export const techStackTools = [
  {
    id: "powerbi",
    name: "PowerBI",
    version: "v2.0",
    category: "visualization",
    categoryLabelKey: "dataAnalytics.stack.tabs.visualization",
    icon: "powerbi",
  },
  {
    id: "python",
    name: "Python",
    version: "v3.12",
    category: "analysis",
    categoryLabelKey: "dataAnalytics.stack.tabs.analysis",
    icon: "python",
  },
  {
    id: "react",
    name: "React",
    version: "v19.0",
    category: "frontend",
    categoryLabelKey: "dataAnalytics.stack.tabs.frontend",
    icon: "react",
  },
  {
    id: "typescript",
    name: "TypeScript",
    version: "v5.6",
    category: "frontend",
    categoryLabelKey: "dataAnalytics.stack.tabs.frontend",
    icon: "typescript",
  },
  {
    id: "supabase",
    name: "Supabase",
    version: "v2.0",
    category: "backend",
    categoryLabelKey: "dataAnalytics.stack.tabs.backend",
    icon: "supabase",
  },
  {
    id: "sql",
    name: "SQL",
    version: "v1.0",
    category: "data",
    categoryLabelKey: "dataAnalytics.stack.tabs.data",
    icon: "sql",
  },
  {
    id: "tailwind-css",
    name: "Tailwind CSS",
    version: "v4.0",
    category: "frontend",
    categoryLabelKey: "dataAnalytics.stack.tabs.frontend",
    icon: "tailwind",
  },
  {
    id: "excel-avanzado",
    name: "Excel Avanzado",
    version: "v1.0",
    category: "analysis",
    categoryLabelKey: "dataAnalytics.stack.tabs.analysis",
    icon: "excel",
  },
  {
    id: "figma",
    name: "Figma",
    version: "v1.0",
    category: "design",
    categoryLabelKey: "dataAnalytics.stack.tabs.design",
    icon: "figma",
  },
  {
    id: "git",
    name: "Git",
    version: "v2.48",
    category: "devops",
    categoryLabelKey: "dataAnalytics.stack.tabs.devops",
    icon: "git",
  },
  {
    id: "power-automate",
    name: "Power Automate",
    version: "v1.0",
    category: "measurement",
    categoryLabelKey: "dataAnalytics.stack.tabs.measurement",
    icon: "automation",
  },
  {
    id: "github",
    name: "GitHub",
    version: "v1.0",
    category: "devops",
    categoryLabelKey: "dataAnalytics.stack.tabs.devops",
    icon: "github",
  },
];
